name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.cfml_engine }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cfml_engine: [lucee@5, lucee@6, adobe@2018, adobe@2021, adobe@2023 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run TestBox
        uses: coldfumonkeh/cfml-testbox-action@v1
        with:
          cfml-engine: ${{ matrix.cfml_engine }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          annotate_only: true
          detailed_summary: true
          check_name: 'TestBox report'
          report_paths: 'testbox.xml'
